INSERT INTO khu_vuc (ten, dia_chi, mo_ta) VALUES
('Khu An Phát', '120 Lê Duẩn, Hải Châu', 'Khu trung tâm gần chợ Cồn'),
('Khu Sinh Viên BK', '35 Tôn Đức Thắng, Liên Chiểu', 'Gần Đại học Bách Khoa'),
('Khu Hòa Khánh A', '210 Âu Cơ, Liên Chiểu', 'Khu sinh viên đông'),
('Khu Green Home', '45 Phạm Văn Nghị, Thanh Khê', 'Gần Đại học Duy Tân'),
('Khu Phước Mỹ', '78 Võ Văn Kiệt, Sơn Trà', 'Gần biển Mỹ Khê'),
('Khu Minh Tâm', '12 Nguyễn Tri Phương, Hải Châu', 'Khu nhà trọ gia đình'),
('Khu Sunrise', '25 Nguyễn Văn Linh, Hải Châu', 'Khu phòng cao cấp'),
('Khu Hòa Minh', '150 Nguyễn Sinh Sắc, Liên Chiểu', 'Gần khu công nghiệp'),
('Khu Thanh Bình', '88 Trần Cao Vân, Thanh Khê', 'Gần trung tâm thành phố'),
('Khu Lotus', '66 Nguyễn Hữu Thọ, Hải Châu', 'Gần sân bay Đà Nẵng'),
('Khu Đông Giang', '102 Lê Thanh Nghị, Hải Châu', 'Gần Đại học Đông Á'),
('Khu Hòa An', '140 Tôn Đản, Cẩm Lệ', 'Khu nhà trọ sinh viên'),
('Khu Riverside', '15 Bạch Đằng, Hải Châu', 'View sông Hàn'),
('Khu Mỹ An', '200 Ngũ Hành Sơn, Ngũ Hành Sơn', 'Gần Đại học Kinh Tế'),
('Khu An Hải', '98 Ngô Quyền, Sơn Trà', 'Khu nhà trọ gần cầu sông Hàn'),
('Khu Hòa Xuân', '55 Phan Đăng Lưu, Cẩm Lệ', 'Khu mới phát triển'),
('Khu Sky Home', '77 Hàm Nghi, Thanh Khê', 'Khu mini apartment'),
('Khu Minh Châu', '35 Lý Tự Trọng, Hải Châu', 'Gần trung tâm hành chính'),
('Khu Ocean View', '120 Hồ Nghinh, Sơn Trà', 'Gần biển'),
('Khu Student House', '50 Trần Đại Nghĩa, Ngũ Hành Sơn', 'Gần Làng Đại học');